### ISSUE TITLE
allow choosing resolution by path regexp

### ISSUE THREAD

**Issue by pyr** [pyr/cyanite#1]
The configuration should allow specifying alternate rollup strategies based on path regexes

**Comment by pyr** [comment]
@chjohnst I'm closing this now as #80 will mark the point at which this is fixed.

**Comment by chjohnst** [comment]
Just looked at #80, will give it a go in my QA env.  Did the schema change
though?

**Comment by pyr** [comment]
Hi chjonst,

Yes, the schema changed, the new schema addresses a number of issues with the original one.
My plans to address the transition are two-fold:

- provide a `cassandra-v1` store which will work with the old schema (not done yet)
- provide a migration tool to be able to use `cassandra-v2`
