### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by shaanaxx** [pyr/cyanite#100]
I am using graphite-web with cyanite and graphite-cyanite. I can successfully insert data into my cassandra cluster. But when I try to retrieve the info using Grafana, I see this error in my graphite exception log. 

  Failed CarbonLink query 'my.queryquerysim.users.allUsers.active'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/graphite/render/datalib.py", line 231, in fetchData
    cachedResults = CarbonLink.query(dbFile.real_metric)
  File "/usr/local/lib/python2.7/site-packages/graphite/render/datalib.py", line 140, in query
    results = self.send_request(request)
  File "/usr/local/lib/python2.7/site-packages/graphite/render/datalib.py", line 163, in send_request
    conn = self.get_connection(host)
  File "/usr/local/lib/python2.7/site-packages/graphite/render/datalib.py", line 130, in get_connection
    connection.connect( (server, port) )
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

Here is my cyanite.yaml

carbon:
  host: "0.0.0.0"
  port: 2003

  rollups:
    - "1s:1h"
    - "10s:14d"
   - "10m:30d"

http:
  host: "0.0.0.0"
  port: 8089

logging:
  level: info
  console: true

  files:
    - "/var/tmp/cyanite.log"

store:
  cluster: 'c02.test.com'
  keyspace: 'metric'
  chan_size: 100000 # defaults to 10000
  batch_size: 500 # defaults to 500

index:
  use: "io.cyanite.es_path/es-rest"
  index: "my_paths" #defaults to "cyanite_paths"
  url: "http://c01.test.com:9200"
  chan_size: 1000 # defaults to 1000
  batch_size: 1000 # defaults to 1000

This is what i added in my local_settings.py in graphite.

STORAGE_FINDERS = (
    'cyanite.CyaniteFinder',
)
CYANITE_URLS = (
    'http://0.0.0.0:8089',
)

**Comment by pyr** [comment]
Hi @shaanaxx,

This seems to be due to a configuration problem but I can't pinpoint it.
