### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mattford63** [pyr/cyanite#102]
Could someone provide some example HTTP queries/uris in the docs?  Would be very helpful in exploring the HTTP API.  I'm struggling to write anything that works other than

```
curl http://localhost:8080/paths
```

**Comment by brutasse** [comment]
The other useful URL is `/metrics` with the `path`, `from` and `to` querystring parameters. If you're looking for graphs it'd probably be easier to use graphite-api and graphite-cyanite to extract data from cyanite and use one of the graphite dashboards.

You can find a usage example in graphite-cyanite: https://github.com/brutasse/graphite-cyanite/blob/master/cyanite.py#L62-L64 and https://github.com/brutasse/graphite-cyanite/blob/master/cyanite.py#L99-L100.

**Comment by mattford63** [comment]
That's been a big help - ty.

**Comment by pyr** [comment]
@mattford63 queries are now documented at http:/cyanite.io as part of #80. Sorry for the wait!
