### ISSUE TITLE
website dead links

### ISSUE THREAD

**Issue by davewood** [pyr/cyanite#107]
on http://cyanite.io/

get started ... http://cyanite.io/quickstart/

and

learn more ... http://cyanite.io/design/

give me 404 errors

**Comment by pyr** [comment]
Hi David,

Unfortunately this needs a lot of work. A new documentation site is in progress, sorry to keep you waiting.

**Comment by pyr** [comment]
Hi @davewood,

There is now a more detailed quickstart and design document at http://cyanite.io which describes the status of cyanite#80
