### ISSUE TITLE
Recommend DateTieredCompactionStrategy in README

### ISSUE THREAD

**Issue by ebpitts** [pyr/cyanite#109]
@pyr I saw you recommended using DateTieredCompactionStrategy in your [talk](https://vimeo.com/131581325) at Monitorama (btw, are the slides available online?). The README still mentions SizeTieredCompactionStrategy, so perhaps it should be changed.

**Comment by pyr** [comment]
Hi @ebpitts, this is now fixed in #80, thanks!
