### ISSUE TITLE
General state of the project

### ISSUE THREAD

**Issue by jippi** [pyr/cyanite#110]
Hi,

I'm looking into using graphite with cassandra, and cyanite looks perfect for it

I have however noticed a lot of open (and old) tickets and PRs for the repo - is the project currently maintained and stable - or should it be considered risky business in production environments ?

**Comment by pyr** [comment]
Hi Christian,

Thanks for your interest in cyanite. The state of the project is stable right now and works for several large deployments.

That being said there are improvements that will be tackled that require a bit of work (without noticeably impacting the schema). This explains the sorry state of the issue tracker and hope it won't deter you from trying out cyanite.

Cheers!
