### ISSUE TITLE
new logo: licence and copyright

### ISSUE THREAD

**Issue by kyzh** [pyr/cyanite#114]
Does the [licence](https://github.com/pyr/cyanite/blob/master/LICENSE) applies to the [logo](https://github.com/pyr/cyanite/blob/master/doc/source/_static/cyanite.png) too ?

**Comment by pyr** [comment]
Hi @kyzh,

The logo's copyright is assigned to @ste-m and he agrees that the license should be Creative Commons, I'll add that to cyanite.io somewhere sometime soon.

**Comment by kyzh** [comment]
thanks :)

**Comment by pyr** [comment]
Of course, if you plan on using it somewhere, we'd love to know!
