### ISSUE TITLE
How to bind on 0.0.0.0

### ISSUE THREAD

**Issue by altvnk** [pyr/cyanite#118]
Is there any way to specify where to bind? By default cyanite binds on 127.0.0.1:2003, but api binds on 0.0.0.0:8080

**Comment by pyr** [comment]
Hi @altvnk,

Yes as described in the docs, you can use the `host` key for api or your `carbon` or `pickle` input to specify the binding address.

Cheers!

**Comment by altvnk** [comment]
Oh, thanks! Maybe it's not all clear in docs? Some examples will omit the questions like this.

**Comment by pyr** [comment]
For reference, the doc is here: http://cyanite.io/administrator.html#configuration-syntax

**Comment by altvnk** [comment]
Thank you a lot, seems like i'm a blind =D
