### ISSUE TITLE
Wrong urls in Releases documentation

### ISSUE THREAD

**Issue by alangibson** [pyr/cyanite#120]
The Cyanite homepage at http://cyanite.io/ says

    The latest release is available at https://github.com/pyr/cyanite/releases/latest

Clicking through to that url results in this message from GitHub

    There aren’t any releases here

The url http://cyanite.io/quickstart.html#obtaining-cyanite says

    Binary release are the simplest way to get started and are hosted on github: https://github.com/exoscale/cyanite/releases/latest.

Clicking through to that url results in a 404 error from GitHub

Could you please update these with the correct location of the binary releases?

**Comment by pyr** [comment]
Hi @alangibson,

This is because there are no binary releases yet, there's a - admitedly small - warning on main page of cyanite.io. The release is imminent though.
