### ISSUE TITLE
Size of batch of prepared statements Cassandra warnings

### ISSUE THREAD

**Issue by dgeorgievski** [pyr/cyanite#122]
Committing data to Cassandra by Cyanite creates this warning:
> WARN  [SharedPool-Worker-1] 2015-08-07 15:37:53,563 BatchStatement.java:252 - Batch of prepared
> statements for [metric.metric] is of size 26000, exceeding specified threshold of 5120 by 20880.

Initially I thought this warning could be easily addressed by setting higher value for this setting in cassandra.yaml
> \# Log WARN on any batch size exceeding this value. 5kb per batch by default.
> \# Caution should be taken on increasing the size of this threshold as it can lead to node instability.
> batch_size_warn_threshold_in_kb: 5

As you can see the comments for the setting recommend not to raise the WARN threshold level to avoid instability with the Cassandra node.

Before I do anything, this issue is not critical, I wanted to check with others and see what they have done to tune the batch size of the prepared statements.

I assume the store batch_size setting (default is 500) is in KB. 

I am running Cyanite 0.1.3 on CentOS 6.6 (2.6.32-504.30.3.el6.x86_64), with Java 8u54 64bit,
and DataStax Cassandra 2.1.8.

Thanks

Dimitar

**Comment by rrudduck** [comment]
Heed the warning in the cassandra.yaml - large batches can do some really bad things to a C* cluster. I set my batch_size in cyanite.yaml to 50. That number depends depends on the size of the data being sent (longer vs. shorter paths) so you can tune it, but 50 works for me.

**Comment by dgeorgievski** [comment]
Thanks @rrudduck. Reducing the store batch_size to 50 eliminated the very frequent WARN message.

**Comment by tjamesturner** [comment]
why not set the batch_size to 1?  there is nothing transactional about the data and there are no duplicate writes to coalesce, so there should be no performance benefit to larger batches only increased coordination costs. am i missing something?

a reference for your consideration:
http://christopher-batey.blogspot.com/2015/02/cassandra-anti-pattern-misuse-of.html

**Comment by pyr** [comment]
@dgeorgievski in the upcoming cyanite release, there are no batches. thanks for reporting.
