### ISSUE TITLE
Netty error message

### ISSUE THREAD

**Issue by AnderEnder** [pyr/cyanite#123]
During the cyanite start:

> ERROR [2015-08-11 09:43:27,959] nioEventLoopGroup-2-2 - io.netty.util.ResourceLeakDetector LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetectionLevel=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

High load on pickle interface
Ubuntu14.04/oracle-jdk-1.8.0_51
cassandra: 2.2.0
cyanite: 0.5.1
elasticsearch: 1.7.1

In my case also notice that all heap memory(any value) was used by cyanite.

**Comment by pyr** [comment]
@AnderEnder interesting, you're pushing a high volume through pickle ? may i ask that you try again now that #134 landed ?
