### ISSUE TITLE
Connection Refused () with load balancers

### ISSUE THREAD

**Issue by gmlwall** [pyr/cyanite#125]
This is probably user error so apologies in advance;

Im trying out Cyanite and want to duplicate our current production traffic to it, sending TCP directly to it i have no issues (echo & netcat) however when trying to load balance the TCP over it i get connection refused. I have tried; HAProxy / carbon-c-relay / carbon-relay-ng all to no avail.

My config;

logging:
  level: info
  console: true
  files:
  \- "/var/log/cyanite/cyanite.log"
inputs:
  \- type: "carbon"
    port: 2013
  \- type: "pickle"
    port: 2014
store:
  type: "cassandra-v2"
  cluster: "10.10.10.10"
index:
  type: "memory"
api:
  port: 8080
engine:
  rules:
    default:
      - "5s:1h"

Am i missing something simple here?

If not...
Id like to scale this over a few cyanite instances as it will have to handle 2M + metrics per min, so if anyone would be kind enough to share a working carbon-relay-ng config i would be very thankful.

**Comment by gmlwall** [comment]
cyanite also seems to ignore any parameters in the config;

i changed the ports around to test somethings, and also the bind address from 127.0.0.1 to 0.0.0.0 as per this config;

logging:
  level: info
  console: true
  files:
   \ - "/var/log/cyanite/cyanite.log"
inputs:
  \- type: "carbon"
    port: 2004
    host: 0.0.0.0
store:
  type: "cassandra-v2"
  cluster: "10.188.241.49"
index:
  type: "memory"
api:
  port: 8080
engine:
  rules:
    default:
      \- "5s:1h"

however looking at netstat, its still bound to 2003/127.0.0.1, even after ensuring all prev processes were killed.

**Comment by gmlwall** [comment]
so further to my port testing;

if i netcat to 
localhost = ok
127.0.01 = ok
0.0.0.0 = ok
IP addr = fail

this would explain why the LB cant connect to it, however as mentioned above its ignoring my config to bind to 0.0.0.0,

**Comment by gmlwall** [comment]
further to this, none of the arguments under 

\- input 

are taken, however the rest seem to apply.

**Comment by gmlwall** [comment]
ok the issue with it not picking up the config was

inputs

should be input

http://cyanite.io/quickstart.html#requirements has the config as inputs and i had copy/pasted that. :)

**Comment by pyr** [comment]
thanks for spotting the error @gmlwall
