### ISSUE TITLE
Stuck in DEBUG / doesnt accept -q arg

### ISSUE THREAD

**Issue by gmlwall** [pyr/cyanite#126]
Even when overriding in the config, the log level is still set to DEBUG.
Passing in the -q option to the jar still outputs everything to the terminal.

**Comment by pyr** [comment]
@gmlwall I can confirm this behavior.

**Comment by pyr** [comment]
The default logging configuration provided an `overrides` key which installed an override for the `io.cyanite` logger, as well as its children. This is now fixed.
