### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by sgran** [pyr/cyanite#143]
Hi,

It looks like the schema has changed incompatibly - this would be fine by itself, but there doesn't seem to be an upgrade path, and I'd rather not lose all my old data.  I briefly considered just reinjecting the data in cassandra to a new version of cyanite and failing over that way, but it seems cyanite sets the ttl based on the receive time, rather than on the time of the metric event (or that's what it looked like when I looked - my clojure-fu is weak), so this would give me double the storage for a while, which won't work for us.

Any ideas?

**Comment by pyr** [comment]
Hi @sgran,

My plan is to provide a `cassandra-v1` store implementation as well which will target the old schema.

**Comment by sgran** [comment]
Hi,

That's also good :)

The new schema looks worthwhile to upgrade to, and I'm happy to put in the time on our side.  I'm just hoping for some help from someone who knows the terrain a bit better so we do it safely.

**Comment by pyr** [comment]
Hi,

The new schema is indeed more interesting in the long run. Is a
double-write scenario feasible for you? If so it might be a good course
of action (i.e: double write until oldest data in cassandra-v1 expires,
then going back to cassandra-v2 writes only).

Cheers!

**Comment by sgran** [comment]
I think that's still double storage - then I might as well just reingest v1 data into the v2-store enabled api.

I'm hoping for a process that looks roughly like:
read in v1 row
write out v2 row into new keyspace or table, setting ttl to ttl of old record
delete v1 row

This sort of operation is expensive on cassandra, I know, but I don't have any other bright ideas.  I also know we'll carry the tombstones for a little while until they get gc'ed, but carrying the data for a few days is a lot better than carrying double data for months.

**Comment by pyr** [comment]
If you go that route, you'll want to use the sstableloader features of
cassandra, which make bulk imports much more efficient. Happy to expand
on this next week.

Cheers!

**Comment by sgran** [comment]
that would be excellent - I look forward to it!

Thanks,
