### ISSUE TITLE
Useful DTCS parameters for the metrics table

### ISSUE THREAD

**Issue by jshook** [pyr/cyanite#147]
This is the configuration I would suggest for compaction on the metrics table only:

    compaction = {'class': 'DateTieredCompactionStrategy', 
    'min_threshold': '12', 'max_threshold': '32',
    'max_sstable_age_days': '0.083', 'base_time_seconds': '50' }

This causes most compaction activity to occur at 10m and 2h windows. If you want to allow 24h windows, simply raise max_sstable_age days to '1.0'.

Note that you must be using Apache Cassandra 2.1 in order to set fractional values for max_sstable_age_days.

**Comment by pyr** [comment]
Hi @jshook,

Would you mind submitting a PR to the documentation sub-directory (`doc`) with this example configuration. This seems like it would be a great addition.

Cheers,
   - pyr

**Comment by jippi** [comment]
I can also recommend not using DTCS at all, and instead use TWCS - https://github.com/jeffjirsa/twcs

**Comment by pyr** [comment]
@jippi what are your thoughts, now that some elements of TWCS have been merged in DTCS?

**Comment by jippi** [comment]
@pyr as long as @jeffjirsa keep maintaining it and moving it along with current cassandra versions, in my experience, its still a lot better and easier for me to manage than DTCS 

used to spend a lot of time on shaky nodes during repair under DTCS, been 0 cases of this since I changed 1 month ago to TWCS :) 

i have not tested DTCS the last 30 days or so, so can't say if its better or not now :)

**Comment by pyr** [comment]
@jippi thanks! it would be great if you were willing to to a small PR to the docs documenting how to add TWCS to the classpath and the appropriate configuration.

**Comment by jippi** [comment]
@pyr sure, but there are 0 cyanite related in changing :) 

I run with the following (install covered by https://github.com/jeffjirsa/twcs)

````
CREATE KEYSPACE metric WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE metric.metric (
    tenant text,
    period int,
    rollup int,
    path text,
    time bigint,
    data list<double>,
    PRIMARY KEY ((tenant, period, rollup, path), time)
) WITH CLUSTERING ORDER BY (time ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"NONE", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'unchecked_tombstone_compaction': 'false', 'tombstone_threshold': '0.2', 'class': 'com.jeffjirsa.cassandra.db.compaction.TimeWindowCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.DeflateCompressor'}
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = 'NONE';
```

**Comment by pyr** [comment]
@jippi Fully agreed, the thing is, many cyanite users come with no cassandra background, hence making documenting these things important. I'll integrate this, thanks!
