### ISSUE TITLE
Better details on pool and queues in the logs

### ISSUE THREAD

**Issue by jshook** [pyr/cyanite#148]
Better details on pools and queues in the log. How full is full? Are these configurable?

    WARN [2015-10-22 05:10:18,227] pool-8-thread-1 - io.cyanite.engine.queue queue is full

This could be related to the issue with *clojure.lang.ExceptionInfo: invalid carbon line: NaN metric* spamming the worker pool.

**Comment by pyr** [comment]
Hi @jshook,

This will soon be added to the documentation and I will provide better defaults for the queue sizes.
I added hints as to what values to use there:

https://github.com/pyr/cyanite/issues/121#issuecomment-145795928

**Comment by pyr** [comment]
this issue is made irrelevant by #174
