### ISSUE TITLE
High Cassandra writes/second

### ISSUE THREAD

**Issue by spynode** [pyr/cyanite#154]
With Cyanite built from develop, when sending ~250K metrics/minute, I see very high Cassandra write operation ratio - 2,5K - 3K writes/second!

My guess would be that Cyanite does not do any sort of write batching and sends individual metric write queries to Cassandra. Eventually, after ~5 minutes Cassandra clogs up (mostly due to GC) and Cyanite throws 

```
com.datastax.driver.core.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out
```

I haven't been able to tune Cassandra to be able to cope with such write load on particular machine.
With same metric amount with KairosDB, for example, there are approx 2-10 writes/second depending on write delay configuration and Cassandra is able to perform adequately.

**Comment by rrudduck** [comment]
Cassandra should easily be able to handle that write load. What kind of machines is your cluster running on?

**Comment by altvnk** [comment]
I have testing lab where Cassandra hits ~40k writes/s (50iops per node disk)
3 instances of Cyanite (512m heap, 0.5cpu each)

**Comment by pyr** [comment]
Thanks for the  report, I'll be closing this for now as we are still doing heavy work on core functionality in cyanite which will change the part responsible for this
