### ISSUE TITLE
io.cyanite.http http server exception caught

### ISSUE THREAD

**Issue by hryamzik** [pyr/cyanite#157]
I get the following error when connecting to graphite-api in grafana direct mode:

```
ERROR [2015-11-03 03:28:54,151] epollEventLoopGroup-3-1 - io.cyanite.http http server exception caught
java.nio.channels.ClosedChannelException: null
```

This also breaks all the graphs. Works fine in proxy mode but.

**Comment by ifesdjeen** [comment]
Unfortunately ATM only the proxy mode is working.

**Comment by pyr** [comment]
Indeed, only proxy mode works reliably for now.
