### ISSUE TITLE
Supported version of cassandra

### ISSUE THREAD

**Issue by ajazam** [pyr/cyanite#162]
Hello,
The cyanite docs which cassandra 2.1 or later are supported. Has anybody tested cyanite with either 2.2 or 3.0?

**Comment by aww-yiss** [comment]
I've tested this out with cassandra 2.1.10 without issues as I'm planning on going to production with this shortly, I don't believe 2.2 or 3.0 are stabile enough for this use case.

**Comment by ajazam** [comment]
Ok. I'll stay with 2.1.x
