### ISSUE TITLE
Add tags for released versions (maybe at least for the last one)

### ISSUE THREAD

**Issue by ifesdjeen** [pyr/cyanite#165]
Hi!

Could you add a git tag for the last released version so that it'd be possible to rely on at least some stability giving the lack of binary releases? This way it'd be possible to integrate building cyanite into some CI pipeline (that some people might want to do) and checkout the tag instead of checking out the commit SHA.

Thanks!

**Comment by pyr** [comment]
Hey!

I plan on doing a tagged release, unfortunately, no official release has been published yet. Cyanite still needs a bit of love in several places before this becomes a reality.

**Comment by ifesdjeen** [comment]
Oh, i see. Do you need help with anything? If there's a roadmap I could help.

**Comment by pyr** [comment]
Help would be great, on several fronts. (I'll need some time to write things down).

**Comment by ifesdjeen** [comment]
You know where to find me :D
