### ISSUE TITLE
Indexes not rebuilt on startup

### ISSUE THREAD

**Issue by ifesdjeen** [pyr/cyanite#171]
Index is at the point not rebuilt at startup, which means that inserted metrics can't be queried after the server restart.

**Comment by pyr** [comment]
The cassandra index - while dog slow at the moment - does that. The default in-memory index does not. The rationale is that in many cases, you are sending metrics at regular interval.

The classic case here is sending the same set of metrics from an agent, upon restart, within two collection intervals, you'll have a full index again.

**Comment by pyr** [comment]
I'll close this for now, and add some documentation bits for the situation.

**Comment by pyr** [comment]
Another avenue which might be worth exploring is triggers on insertions, though this means modifying cassandra's classpath.
