### ISSUE TITLE
Avoid excessive GC pressure for events

### ISSUE THREAD

**Issue by pyr** [pyr/cyanite#175]
We currently create a new `clojure.lang.Volatile` for every incoming event on a queue. Down the road this could have some serious GC impact for high traffic queues.

@ifesdjeen summed up nicely the path from our current situation. No rush for now, this issue serves as a reminder for future work:

> In reactor, you can "lend" the objects, modify them and then publish (this is hidden behind the
> disruptor dsl for now). So in essence, I'd lend a metric object from the queue, set all the required 
> fields there and then publish. This way we avoid recreating it. Of course that'd mean larger initial 
> queue size but in a long term it pays off :)

**Comment by ifesdjeen** [comment]
Would you like me to check that one out?

**Comment by pyr** [comment]
Sure, if you want to tackle it. although i'd say optimization in this area can probably be held off for a while. I think testing the snapshot mechanism in `io.cyanite.engine.buckets` and extending the DSL support for grafana integration might be a better focus for now.

**Comment by ifesdjeen** [comment]
ah ok, true true

**Comment by ifesdjeen** [comment]
I think that one is mostly handled: volatile is created once per RingBuffer slot, and GC pressure is generally handled by avoiding window collection.
