### ISSUE TITLE
Consider removal of pickle input

### ISSUE THREAD

**Issue by pyr** [pyr/cyanite#176]
Since the `carbon-c-relay` project can act as a proxy for systems emitting pickle data and the interest of parsing pickle is debatable within cyanite (`pickler` is far from perfect as it stands). This would set appropriate expectations for users of cyanite and allow the development effort to focus on other aspects for now, especially getting ready for integration with grafana.

**Comment by ifesdjeen** [comment]
I'd say if it helps to bring cyanite up-to-speed, I'd remove it for now and when we have more resources and the rest of thigns are settled down we can bring it back or redevelop

**Comment by pyr** [comment]
Yup, we seem to agree on the appropriate course, just wanted to run it by you.

**Comment by ifesdjeen** [comment]
<3
