### ISSUE TITLE
Use "another" ring buffer queue for runnables?

### ISSUE THREAD

**Issue by ifesdjeen** [pyr/cyanite#180]
Do you think it might be a good idea to use one more ring buffer queue for the runnables (currently clojure agents are used in index and drift). Might be a senseless optimisation in case of drift, since theoretically this part should not happen to often, although with index recalculation - it happens a bit more often as far as i understand.

**Comment by pyr** [comment]
I think instrumentation will tell us where we spend most of our time and would not focus on this part for now. With drift I think the answer is sufficient as-is. Start with the agent drift, but eventually clocks should be synced.
