### ISSUE TITLE
High load average

### ISSUE THREAD

**Issue by altvnk** [pyr/cyanite#197]
I've found that on machines where cyanite is running load average grows really fast (10-12 on 5min average, 2 CPU's). What i've found next is too much `TIME_WAIT` connections witch causes CPU waits as i understand. My assumption that cyanite is not properly closes network connections, but i may be wrong.

**Comment by ifesdjeen** [comment]
Which version would that be? Same as in the issue you've previously reported?

**Comment by altvnk** [comment]
Right, the same. I have to say that I have seen this earlier, I just wasn't sure what caused such load. We are running cyanite and some other stuff on testing Mesos cluster, so there was too much additional factors. But after some cleanup problem is obvious and reproducible.

**Comment by ifesdjeen** [comment]
Great, thanks! I'm extensively perf testing and doing lots of tuning on different parts as you can see from the outstanding PRs, but pointers like that are extremely useful.

**Comment by altvnk** [comment]
Sure, np. I'm very interested in this project and will contribute as much as I can. I cannot code, so reporting issues might be helpful I think :)

**Comment by ifesdjeen** [comment]
Should be fixed as well. Will be improved further with caches.
