### ISSUE TITLE
Cyanite schema.sql caching "SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message="Invalid value for property 'caching'. It should be a map.">"

### ISSUE THREAD

**Issue by seapasulli** [pyr/cyanite#199]
when I tried to import your schema.sql file cassandra 3.0.3 errored. I updated schema.sql's caching lines to be the following":
     `AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
`
and then it worked without issues.

**Comment by ifesdjeen** [comment]
Unfortunately that would not work for cassandra 2.x, which is our current target. 
We're going to be migrating to 3.4 as soon as it's released, skipping all the versions inbetween, due to the sasi index.

**Comment by seapasulli** [comment]
Sorry to resurrect. Can we update the docs to exclude 3X for now. At least until 3.4 support is added? I just feel that it is vague. Sorry to bug or request anything on this as it is free and I am grateful, I just think it would help other lowly sysadmins like myself.

**Comment by ifesdjeen** [comment]
@seapasulli we haven't merged it yet, mostly because I've made a mistake of using bloom filter with inverted logic. I hope to be able to fix it at least partially shortly...
