### ISSUE TITLE
cyanite vs. kairosdb?

### ISSUE THREAD

**Issue by KlavsKlavsen** [pyr/cyanite#202]
I just found kairosdb.. also using cassandra as backing store.. any comparison thoughts?

**Comment by rsvancara** [comment]
Definitely appears to be a much more mature product.  Right now the performance of cyanite in terms of reading metrics using Cassandra 3.4. Cyanite does not appear to have much activity.

**Comment by justanyone** [comment]
We had very little luck with either product.  We're using catsdb now.

**Comment by ifesdjeen** [comment]
I'm not sure what catsdb is to be honest, never heard of it. Google and github searches yielded no information either. Cyanite didn't yet have any official release, so it's experimental software. We're getting it more stable. Last bits are coming along quite well. We hope to have it stabilized soon.

**Comment by ifesdjeen** [comment]
Sorry for closing it. I think at this particular moment it's better to avoid strong comparisons or make any big claims. In short, sweetspot of cyaite is being lightweight and fully compatible with Graphite infrastructure.
