### ISSUE TITLE
Documentation on HTTP API

### ISSUE THREAD

**Issue by MichaelHierweck** [pyr/cyanite#206]
There seem to be changes to the HTTP API that broke integration with graphite-api. These changes lack documentation of the API itself and how to connect clients.

Is cyanite going to make graphite-api obsolete by implementing the "Graphite API" itself?

**Comment by ifesdjeen** [comment]
Could you be more specific? To be honest, I'm  not using graphite-api, although I can't think where exactly it might deem to be useful.

**Comment by MichaelHierweck** [comment]
We use graphite-api in order do be able to connect graphite-web (or maybe other tools providing a web based ui for graphs based on data provided by cyanite.

Full stack:

collectd -f-> riemann -f-> cyanite <-q- graphite-api <-q- graphite-web (or may other frontend)

f=  forward
q = query

Examples for incompatibility between cyanite and graphite-api (to be more precise: the graphite-cyanite plugin used with graphite-web)

a)  When quering for paths cyanite retrun a list of dictionaries (maps). Graphite-aynite expects a map key called "path" which seems to be provided as "id".

curl http://127.0.0.1:8080/paths?query=com.example.host.load

b) When querying for metrics, no data but an empty error message is returned.
curl "http://127.0.0.1:8080/metrics?path=com.example.host.load&from=1462544152&to=1462544162

However, this (http://cyanite.io/api.html) piece of documentation seems to be outdatet. Can you provide up to date examples for communication with the API?

OT: You don't use graphite-api. Can you suggest any leightweight graphing tool that can work with the HTTP API of cyanite (directly)?

**Comment by ifesdjeen** [comment]
At least up till the date I've been mostly testing against `grafana` (although in proxy mode). APIs should (usually) be still compatible with `graphite-api`, too (at least that's the goal), so I'm going to investigate the behaviour. 

Thank you very much for reporting!

**Comment by MichaelHierweck** [comment]
Should Cyanite bring back the "path" key or should cyanite finder adopt "id"?

**Comment by brutasse** [comment]
If backwards compatibility is easy, it'd be nice to have "path" again.

**Comment by ifesdjeen** [comment]
I agree. I'll bring it back.

**Comment by ifesdjeen** [comment]
Feel free to submit a pr @MichaelHierweck if you feel like it)

**Comment by MichaelHierweck** [comment]
Sorry, no idea whether renaming "id" to "path" would break other components such as grafana.

**Comment by ifesdjeen** [comment]
:) no problem

**Comment by MichaelHierweck** [comment]
There seem to be even more incompatibilities. Please simply try [graphite-api's Render API](http://graphite-api.readthedocs.io/en/latest/api.html#the-render-api-render) using the upstream Cyanite Finder against upstream Cyanite.

Since the HTTP API appears to work with grafana, I'd tend to fix the Cyanite Finder.

I was not able to figure out what's excatly wrong.

**Comment by brutasse** [comment]
> Since the HTTP API appears to work with grafana

Are you sure? AFAIK Grafana isn't able to talk to cyanite directly and needs the graphite-api+cyanite finder components.

POST requests to `/render` is for graphite/graphite-api, interface documented [here](http://graphite-api.readthedocs.io/en/latest/api.html#the-render-api-render).

**Comment by MichaelHierweck** [comment]
Cyanite's HTTP API seem to have envolved so that Grafana can talk directly do Cyanite. (At least it worked for me when graphite-api was disabled complety. I guess these changes broke the Cyanite Finder for graphite-api. Cyanite does not implement the graphite API specification.

Questions:
- Will Cyanite implement the complete graphite API specification soon? (This would make graphite-cyanite (finder) obselete as Cyanite would "talk graphite" on its own.)
- If not, what needs to be done to fix graphite-cyanite? (My [PR](https://github.com/brutasse/graphite-cyanite/pull/21) fixes graphite-cyanite so that the /metrics/.... part of the API works again, but the /render/... part still does not because the remote call on [line 113](https://github.com/brutasse/graphite-cyanite/blob/master/cyanite.py#L113) fails and I suppose the one on [line 62](https://github.com/brutasse/graphite-cyanite/blob/master/cyanite.py#L62) will fail, too.

**Comment by MichaelHierweck** [comment]
Thanks for #213. Is this intended to fix the above mentioned bug related to graphite-apis render api, too?

**Comment by ifesdjeen** [comment]
Yes. I think it does fix it in fact. Feel free to close.

**Comment by ifesdjeen** [comment]
Oh wait, documenting :)

**Comment by MichaelHierweck** [comment]
I can confirm the setup graphite-api -> cyanite finder -> cyanite works for both metrics and render API with the current upstream version. Great!

**Comment by ifesdjeen** [comment]
I'm closing then?

**Comment by MichaelHierweck** [comment]
Feel free to close this issue. :)
