### ISSUE TITLE
Question: Cleanup

### ISSUE THREAD

**Issue by MichaelHierweck** [pyr/cyanite#214]
Does Cyanite automatically purge outdated metrics?
Does Cassandra need explicit compaction or any kind of vacuuming?

**Comment by ifesdjeen** [comment]
What do you mean by "outdated metrics"?

**Comment by MichaelHierweck** [comment]
I mean metrics beyound the speficied ranges. E.g. [1m:5d] => what happens to metrics older than 5 days?

**Comment by ifesdjeen** [comment]
They get TTLed, after that Cassandra compaction kicks in to remove them.

**Comment by ifesdjeen** [comment]
More information on the subject can be found here: https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_expire_c.html
