### ISSUE TITLE
Parse floats for timestamps

### ISSUE THREAD

**Issue by jjneely** [pyr/cyanite#220]
Looks like there are quite a few cases in my environment where the timestamp in the carbon line protocol is a float value.  Graphite accepts these values and parses them correctly.  With the current master I get the following exception:

```
WARN [2016-07-18 19:43:39,222] nioEventLoopGroup-2-14 - io.netty.channel.DefaultChannelPipeline
 An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. clojure.lang.ExceptionInfo: invalid time
```

**Comment by ifesdjeen** [comment]
Right. That should be quite simple to fix...

**Comment by jacobrichard** [comment]
The above is a pull request that should allow just that. I'm no clojure developer, but it works in my testing.

**Comment by ifesdjeen** [comment]
Sure, that's a great patch :) thank you
