### ISSUE TITLE
Typo in index.clj

### ISSUE THREAD

**Issue by marchnikolai** [pyr/cyanite#243]
root@localhost:~/cyanite# git diff
`diff --git a/src/io/cyanite/index.clj b/src/io/cyanite/index.clj
index 6a9d48c..1b5c7ea 100644
--- a/src/io/cyanite/index.clj
+++ b/src/io/cyanite/index.clj
@@ -106,7 +106,7 @@
     {:path         path
      :text         (last (split path #"\."))
      :id           path
-     :allowChilren (if (some (partial < length) lengths) 1 0)
+     :allowChil**d**ren (if (some (partial < length) lengths) 1 0)
      :expandable   (if (some (partial < length) lengths) 1 0)
      :leaf         (if (boolean (lengths length)) 1 0)}))
`

**Comment by ifesdjeen** [comment]
Thanks! Would you like to submit it in a form of a patch?
