### ISSUE TITLE
Does Cyanite support custom metrics as attached

### ISSUE THREAD

**Issue by priyavivek1** [pyr/cyanite#268]
![image](https://cloud.githubusercontent.com/assets/12853774/24017281/bfb9769e-0a65-11e7-8c6f-59035e759c96.png)

i am looking forward to store my metrics this way.will cyanite support this since reading schema.cql doesnt seem to be doign so?

**Comment by ifesdjeen** [comment]
@priyavivek1 could you explain what exactly you're expecting? Which way? You would like to have multiple metrics per timestamp?

**Comment by priyavivek1** [comment]
So, iur requirement is to capture multiple fields from request like in attached screenshot and then capture metrics like request count.

if you see first record in atached image, its capturing the metrics that

for a particular API i.e api-mgmt-info, where client id sent in request was "testscopeClient" with endpoint "/api/info" and other parameters, total number of request was "3" in a confugred time interval.

for example: betweeen 10:05am - 10:10 am (5 minutes gap), there were 3 request with specified clientid, appiid, etc

Hope it clarifies, Will we be able to achieve this using cyanite.

**Comment by ifesdjeen** [comment]
You can find a feature complete description of Cyanite here: http://cyanite.io/
If you have a concrete feature request, feel free to open an issue.
