### ISSUE TITLE
Internal Metrics

### ISSUE THREAD

**Issue by feangulo** [pyr/cyanite#27]
When a carbon process is spun up, it reports a bunch of useful metrics that can be used to monitor the health of the process (see screenshot for a few).

Does a cyanite process expose any of its internal metrics?

![screen shot 2014-04-02 at 11 42 23 am](https://cloud.githubusercontent.com/assets/5490207/2593196/838471be-ba7d-11e3-9d0c-8592e0ad7f6d.png)

**Comment by pyr** [comment]
@feangulo I started metric integration

**Comment by ifesdjeen** [comment]
My current "solution" is using Graphite reporter: http://metrics.dropwizard.io/3.1.0/manual/graphite/ 

Do you think it might be useful to make it configurable (e.g. off by default but one can turn it on any time)

**Comment by pyr** [comment]
@ifesdjeen I want to rely on https://github.com/pyr/reporter which is has opt-in support for different reporters.

**Comment by ifesdjeen** [comment]
ah, true :) now I can connect the dots :D

**Comment by ifesdjeen** [comment]
great idea, perfect
