### ISSUE TITLE
io.cyanite.engine.writer starting snapshot

### ISSUE THREAD

**Issue by 1stdemon** [pyr/cyanite#272]
Hello,

Cyanite 0.5.1 every second write in log file string "cyanite-snapshot - io.cyanite.engine.writer starting snapshot." is where any way to disable this messages in logs ?

**Comment by ifesdjeen** [comment]
We should convert it to `DEBUG`. Want to submit a PR?

**Comment by ifesdjeen** [comment]
Fixed with the latest engine
