### ISSUE TITLE
Support Cassandra Cassandra 2.0.17.1420?

### ISSUE THREAD

**Issue by XiyuanHu** [pyr/cyanite#275]
Hi, 
I have two Cassandra cluster installed as below. Does cyanite compatible with both of them?

[cqlsh 3.1.7 | Cassandra 2.0.17.1420 | CQL spec 3.0.0 | Thrift protocol 19.39.0] 
[cqlsh 5.0.1 | Cassandra 2.2.3 | CQL spec 3.3.1 | Native protocol v4]

**Comment by ifesdjeen** [comment]
No, Cyanite works with Cassandra starting 3.4.
