### ISSUE TITLE
cyanite Installation 

### ISSUE THREAD

**Issue by aliartiza75** [pyr/cyanite#280]
Hello, 
I am new to cyanite. I am not able to figure out how to install and run cyanite on my local machine (ubuntu 16.04) with Cassandra 3.11.0 and Java 1.8.0_131. I have already searched the web and unable to find a good resource that guides me how to do that. I have used these following links but I am confused.

How to install graphite api
	http://graphite-api.readthedocs.io/en/latest/installation.html
Grphite-api details
	https://github.com/brutasse/graphite-api
How to install libffi-dev 
	https://www.howtoinstall.co/en/ubuntu/trusty/libffi-dev
How to make cluster
	http://linuxczar.net/blog/2016/07/17/installing-cyanite-a-scalable-graphite-storage-backend/
Cyanite details
	https://github.com/pyr/cyanite
leining
	https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md
	https://leiningen.org/
leining usage
	https://github.com/technomancy/leiningen
Closure
	https://clojure.org/

Guys if you have anything related to cyanite installation and usage, kindly share it.

Thank you

**Comment by ifesdjeen** [comment]
There's no official release for now. You would have to clone the repository and build a jar with `lein uberjar` yourself.

**Comment by aliartiza75** [comment]
ok :+1:
