### ISSUE TITLE
TTL for metric tree objects (ElasticSearch)

### ISSUE THREAD

**Issue by dene14** [pyr/cyanite#45]
There is planned to set/update TTLs in ES, however after recent patch https://github.com/pyr/cyanite/pull/36 'index/present' used to avoid excessive updates. This logic breaks an ability to maintain tree objects' TTLs properly.

Any ideas on how to maintain tree index now?

**Comment by pyr** [comment]
@pdolan this is actually more of a question of attaching TTLs to inserts in elasticsearch documents

**Comment by pyr** [comment]
I'm moving this to the next release since the current codebase will need a bit more changes.

**Comment by pyr** [comment]
Now integrated in what will be 0.5.1
