### ISSUE TITLE
Rollups Clarification

### ISSUE THREAD

**Issue by tmonk42** [pyr/cyanite#46]
So my test cluster has been filling up it's disks at a rate MUCH higher than I expected. I went digging to see how the data was actually being stored in Cassandra. I was pretty surprised when I saw that the lower resolution "rollups" were simply a row with an array, "data", that contains every single value for that path during the time period. i.e.:
Given sending stats every 10s (i.e.: with statsd)
rollups defined in cyanite.yaml:
10s:1d = 8,640 rows (each row with 1 value in "data")
1m:7d = 10,080 rows (each row with 6 values in "data")
5m:365d = 525,600 rows (each row with 30 values in "data")
So for each unique metric at the end of a year, I would have 544,320 rows, with 15,837,120 values total in the "data" arrays.

When querying a "lower resolution" value (i.e.: 5m in my example), I believe cyanite is returning the average of the values in that row's "data" array.

Is this correct?

**Comment by ebpitts** [comment]
For clarification: when returning the data for a rolled-up time period, cyanite always returns the average of the datapoints? It's not possible to selectively use other aggregation methods like minimum or maximum?

**Comment by pyr** [comment]
@ebpitts the `agg` query arg can be used to specify min or max as an aggregation method.

**Comment by tjamesturner** [comment]
it is worth noting that you can work around this limitation by using multiple carbon-c-relays and multiple cyanites to pre-aggregate data in the larger retention periods.  

basically, you configure a carbon-c-relay/cyanite pair for each retention period to handle incoming metrics (write requests). then you have 1 more cyanite to handle read requests.  each write cyanite only knows about a single retention period and the matching carbon-c-relay is configured with that same single rollup. the read cyanite knows about all the retention periods.  

you might also want an extra carbon-c-relay simply to duplicate incoming metrics and dispatch them to each rollup-specific relay. alternatively, you could have each of the smaller rollup relays dispatch both to it's cyanite and the next-larger-rollup relay (essentially cascading rollups). this gives you slightly less meaningful weighting of the averages, but matches the values produced by read-aggregation (the ootb single-cyanite weighting) and reduces cpu load. 

you could probably do something very similar using carbon-relay and carbon-aggregator.
