### ISSUE TITLE
pickle receiver support?

### ISSUE THREAD

**Issue by ctavan** [pyr/cyanite#48]
I am currently running a carbon-relay -> carbon-aggregator -> carbon-cache setup and since carbon-cache performs poor I am looking into alternative backends.

To be able to use cyanite as a carbon-cache replacement it needs to accept metrics in as python pickles since this is how carbon-aggregator forwards metrics to carbon-cache.

I have found your interesting blog-post [1] about the python pickle format but I wasn't able to find out if it is already possible, and if so how, to configure cyanite to accept carbon's pickle output.

It would be great if you could give me a hint. I'm happy to contribute documentation updates as a pull request if you could point out here how to achieve this.

[1] http://spootnik.org/entries/2014/04/05_diving-into-the-python-pickle-format.html

**Comment by pyr** [comment]
@ctavan I'll close this issue for now, #80 will be your reference point. I expect to release this weekend.
