### ISSUE TITLE
add carbon udp support

### ISSUE THREAD

**Issue by pyr** [pyr/cyanite#5]

**Comment by pyr** [comment]
Not sure if this is needed at all, will close for now.

**Comment by emanuelis** [comment]
Needed

**Comment by pyr** [comment]
Hi @emanuelis,

Can you explain what motivates the need in your opinion?
In any case this will be pushed to a later release.

Cheers!

**Comment by emanuelis** [comment]
Thousands of monitored hosts via mobile/slow internet having very limited resources.

**Comment by pyr** [comment]
@emanuelis Thanks, I'm happy to reconsider this choice. I will make the necessary changes to finish up the first release and will integrate this in the next one.

**Comment by chrissnell** [comment]
+1 for this  :)
