### ISSUE TITLE
Request: on startup, when keyspace isn't inited, either exit or retry connections

### ISSUE THREAD

**Issue by jpotter** [pyr/cyanite#56]
We're seeing a minor bug when running cyanite in a testing setup, where the testing setup resets and re-inits everything.

Specifically, if the metric keyspace doesn't exist right at startup of cyanite (because our init scripts are running it at the same time -- so we can fix this by delaying the startup of cyanite), then the below stack trace occurs *and* the process hangs. I'd suggest either having cyanite exit, or retry on some interval, and on success, continue. As it is now, the process spins up, but fails to reach a point where it's listening on any ports for traffic.

-J

DEBUG [2014-09-19 10:15:58,545] main - org.spootnik.cyanite.config - building  :store  with  org.spootnik.cyanite.store/cassandra-metric-store
INFO [2014-09-19 10:15:58,558] main - org.spootnik.cyanite.store - creating cassandra metric store
	at org.spootnik.cyanite.config$init.invoke(config.clj:124)
	at org.spootnik.cyanite$_main.doInvoke(cyanite.clj:31)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at org.spootnik.cyanite.main(Unknown Source)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'metric' does not exist
INFO [2014-09-19 10:15:58,558] main - org.spootnik.cyanite.store - creating cassandra metric store

**Comment by pyr** [comment]
fixed in #80 by b2587435fd57712949a441870ef2132864d55587
