### ISSUE TITLE
Allow for time points in paths query

### ISSUE THREAD

**Issue by sgran** [pyr/cyanite#71]
graphite-api supports queries to find paths during a given time period of the form:
```
/metrics/find/?query=*.*.*.*&from=then&until=now
```
It would be great if the paths method could have optional time parameters to allow callers to restrict the set of metrics to the ones valid during a given time period.  I'm using graphite-cyanite at the moment, and it can't pass this information back in the query, although the information is available.

Thanks!

**Comment by sgran** [comment]
Any thoughts on this?  I have to periodically clean out the index right now, which is a bit tedious and error prone.  Is there anything I can do to help push this forward a bit?

**Comment by ifesdjeen** [comment]
To be honest, I can not see any way to allow this change in a performant manner. the only way to do this is to run queries for the paths first and then to re-run the same the query in the metrics table to check if this metric was or was not active. 

Maybe @pyr has an idea on how to implement it in a performant fashion?

**Comment by ifesdjeen** [comment]
@sgran if I understand the problem correctly, your problem is that you have some short-lived metrics, and you'd like to expire them after the certain time period, am I correct? Or you just have metrics that come and go absolutely unpredictably?

**Comment by sgran** [comment]
we use the hostname or hostid in the metric path.  With a combination of containers and cloud hosts, we get a high rate of churn on metric paths.  The actual metrics themselves expire when the ttl expires, but the paths index in elasticsearch is an ever-growing set.  Also, a query for a half hour window of metrics gets a list of all available paths, and then does a cassandra for all of those paths in the half hour window, even though only a tiny subset of them exist in that window.  This is not particularly efficient :)

**Comment by ifesdjeen** [comment]
I'd recommend prefixing your metric with hour or day for search purposes. Other than that they should not impair performance or GC metrics manually or expire them by simply adding a TTL on the table-level during the creation (by simply changing the schema).

Described use-case is not something typical for the time series and path store.

**Comment by sgran** [comment]
cyanite with the graphite middle ware makes it impossible to do aggregate reporting of metrics if you don't encode the hostname in the metric path - the default behaviour is to take the mean of all values in a time bucket, and graphite-api / graphite-cyanite doesn't expose a way to change that.

This means that if you want to see, say, the total volume of requests across all hosts, you need a unique identifier in the metric path to make them distinct.  This is where we are running into trouble, just so we are clear here - we have a high rate of change in the unique identifier per host.

It's fine if you close this as not a use case you are interested in.  It just means I am going to stop looking for an answer here and go look at other solutions.

Cheers,

**Comment by pyr** [comment]
Hey @sgran,

This is something we have thought about solving by introducing a different way to name metrics. The change will require some time to roll-out though,

**Comment by ifesdjeen** [comment]
@sgran I'm definitely not opposed to have that feature. I just do not have capacity to implement this feature at the moment. If you like - we're an open source project, you can always contribute it.

To be honest, I was not aware of this feature in graphite-api. If it is there, we'll have it sooner or later.

**Comment by asafm** [comment]
What makes your host change so frequently?
How many distinct values do you have per day?
