### ISSUE TITLE
cassandra complains about big batches of prepared statements

### ISSUE THREAD

**Issue by mabrek** [pyr/cyanite#73]
Here's an example from cassandra logs:

    WARN  13:54:22 Batch of prepared statements for [metric.metric] is of size 15496, exceeding specified threshold of 5120 by 10376.
    WARN  13:54:23 Batch of prepared statements for [metric.metric] is of size 15652, exceeding specified threshold of 5120 by 10532.

batch function from store.clj creates BatchStatements using default constructor which results in LOGGED batches. Logged batches have significant ovehead in the way they handled by cassandra (http://www.datastax.com/documentation/cql/3.1/cql/cql_reference/batch_r.html). I'm not familiar with closure enough to find out if updates are done using the same key (as explained in  http://www.datastax.com/documentation/cql/3.1/cql/cql_using/useBatch.html) or not.
There is a good explanation on why it's better to use simple inserts instead of batches with different keys:
http://lostechies.com/ryansvihla/2014/08/28/cassandra-batch-loading-without-the-batch-keyword/

**Comment by jippi** [comment]
bump bump

**Comment by pyr** [comment]
Hi,

I will be closing this, since batches have been deprecated by the cassandra team and I've opted for binding on prepared statements. (approach described in #80)

Sorry for the long wait
