### ISSUE TITLE
Fails when a cassandra node goes down

### ISSUE THREAD

**Issue by MichaelHierweck** [pyr/cyanite#76]
Cyanite fails when a cassandra nodes goes down even if redundancy/consistency are still satisfied.

Configuration:

Cyanite is connected to a local cassandra instance (A) which is connected with two other cassandra nodes (B, C).

cyanite.yaml
```
carbon:
  host: "127.0.0.1"
  port: 2004
  rollups:
    - "1m:30d"
    - "5m:90d"
http:
  host: "127.0.0.1"
  port: 8000
logging:
  level: warn 
  console: true
  files:
    - "/var/log/cyanite/cyanite.log"
store:
  cluster: 'localhost'
  keyspace: 'metric'
  chan_size: 10000 
  batch_size: 1000
index:
  use: "io.cyanite.es_path/es-rest"
  index: "cyanite_paths"
  url: "http://localhost:9200"
```

Cassandra:
```
CREATE KEYSPACE metric WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3};
```

Note: replication factor 2 makes no difference.

Steps to reproduce:

1. All cassandra nodes up (check with nodetool)
2. Start cyanite
3. Take down either node B oder node C

Cyanite fails with:

```
async-dispatch-29 - io.cyanite.store - Cassandra error
clojure.lang.ExceptionInfo: Query execution failed {:values nil, :query #<BatchStatement com.datastax.driver.core.BatchStatement@48b34d74>, :type :qbits.alia/execute, :exception #<NoHostAvailableException com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)>}
	at clojure.core$ex_info.invoke(core.clj:4554)
	at qbits.alia$ex__GT_ex_info.invoke(alia.clj:167)
	at qbits.alia$ex__GT_ex_info.invoke(alia.clj:169)
	at qbits.alia$execute_chan$reify__6658.onFailure(alia.clj:300)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

This failure persistents even when all node are available again.

Strange behaviour:

When cyanite is started while node B or node C are already down no errors appear. It's possible to take node B or C up and down with no side effects on cyanite then.

I tried  passing ":consistency: any" to all alias/execute(-chan) calls but this did no help.

**Comment by MichaelHierweck** [comment]
@pyr: #80 did not help, I'm afraid to say.

**Comment by MichaelHierweck** [comment]
Please merge *both* PR #80 and #88.

**Comment by pyr** [comment]
@MichaelHierweck would you be willing to take a look at this updated #80 ? If so I'll integrate your work from #88. Sorry about the big lag, but I'm ready to move forward and release based on #80 shortly. I'll close this for now since it's not relevant in the context of cyanite's next version.
