### ISSUE TITLE
Intermittent max requests per destination 1024 error

### ISSUE THREAD

**Issue by sreedhardasi** [pyr/cyanite#78]
I am getting the following error intermittently. I am sending around 200K/min metrics and using elasticsearch as path store. Can you help me fix the issue?

DEBUG [2014-11-12 16:49:17,915] async-dispatch-10 - io.cyanite.es_path - Failed bulk update, full response:  {:error #<Result Result[HttpRequest[POST /cyanite_paths/path/_bulk HTTP/1.1]@11d17ac9 > HttpResponse[null 0 null]@4fd42b42] java.util.concurrent.RejectedExecutionException: Max requests per destination 1024 exceeded for HttpDestination[http://10.50.133.241:9200],queue=1024,pool=ConnectionPool[c=64/64,a=64,i=0]>}

**Comment by pyr** [comment]
Hi @sreedhardasi,

This concerns is adressed in #80 - or rather, will be as soon as the ES index makes it back.
