### ISSUE TITLE
Rollups and periods  for particular metrics

### ISSUE THREAD

**Issue by ajazam** [pyr/cyanite#82]
Is it possible to specify different rollups for different metrics?

If you look at the graphite documentation http://graphite.readthedocs.org/en/latest/config-carbon.html#storage-schemas-conf

You can specify

[garbage_collection]
pattern = garbageCollections$
retentions = 10s:14d

I'd like to be able to do that for particular metric patterns.

Is it possible to do this?

**Comment by resnostyle** [comment]
Cyanite is presently not able to handle regexp rollups.

**Comment by pyr** [comment]
Hi @ajazam this will be available as part of #80, thanks!
