### ISSUE TITLE
loosing metrics

### ISSUE THREAD

**Issue by luxifr** [pyr/cyanite#85]
Hi there,

I'm loosing metrics simmilar to the already closed #44 with current master. Unfortunately there's no errors in the logs. 

However, it got worse the more "sources" I add to the system, i.e. more metrics are sent. It seems like it cannot keep up, but I don't know how to debug this. Neither Cassandra nor my disk is anywhere near its limits.

What can I do?

**Comment by pyr** [comment]
Hi @luxifr, this behavior will most likely be fixed by #80. Thanks for reporting and sorry for the wait.
