### ISSUE TITLE
log rotation

### ISSUE THREAD

**Issue by ogg1e** [pyr/cyanite#86]
I don't believe the cyanite log file is being rotated. It could fill up the disk eventually.

**Comment by pyr** [comment]
Hi @ogg1e,

As part of #80, cyanite will support rotation since it relies on https://github.com/pyr/unilog.

Thanks and sorry for the long wait.

**Comment by ogg1e** [comment]
Woot! Great news. Thanks @pyr  . I'll be implementing this new release and testing it once it's done.
