### ISSUE TITLE
updated-core: Channels do not work

### ISSUE THREAD

**Issue by MichaelHierweck** [pyr/cyanite#91]
I recently tried to figure out why no metrics are send to cassandra in the updated-core branch.

I figured out two points:

First: No data will be send to the channel when using the line pipeline becaue the condition in tcp.clj line 43 will not be (never be?) fulfilled:
https://github.com/pyr/cyanite/blob/feature/updated-core/src/io/cyanite/transport/tcp.clj#L43

Second: Despite of the first point there seems to being something wrong with concurrency/channels as the invocation of (a/alts chans) in engine.clj line 50 never returns/waits forever:
https://github.com/pyr/cyanite/blob/feature/updated-core/src/io/cyanite/engine.clj#L50

**Comment by pyr** [comment]
Hi @MichaelHierweck,

Thanks for reporting this. My naive approach to #80 has been udpated and changed to be more reliable (at the expense of a breaking schema change).
