### ISSUE TITLE
Rollups not applied correctly

### ISSUE THREAD

**Issue by resnostyle** [pyr/cyanite#99]
Upon further investigation of our current issue, https://github.com/pyr/cyanite/issues/98 we have determined that rollups are incorrectly applied.  

Our current rollups are:

carbon:
  host: "0.0.0.0"
  port: 2044
  rollups:
    - "30s:1h"
    - "5m:7d"
    - "4h:90d"
    - "1d:10y"

The first hour will be applied correctly but then going further out we are noticing the data starts to become inconsistent and causes certain functions not to work correctly.

**Comment by mwmanley** [comment]
I have been finding that not-using the carbon-style rollups worked for me, as well as specifying the TTL:

  rollups:
    - period: 10
      rollup: 86400
      ttl: 86400
    - rollup: 300
      period: 5184000
      ttl: 5184000
    - rollup: 600
      period: 157680000
      ttl: 157680000

I know it's a pain, but maybe try that as a workaround for now?

**Comment by pyr** [comment]
This is now fixed in #80.
